name: 'Checkout'
description: 'Action for checkout of repository which contains submodules'
inputs:
  repo:
    required: true
  token:  
    required: true
  ref:
    default: master

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        repository: ${{ inputs.repo }}
        ref: ${{ inputs.ref }}
        token: ${{ inputs.token }}
    - run: git submodule update --init --remote --recursive
      shell: bash
      
