
name: CI


on: 
  
  workflow_call:
    
  
  workflow_dispatch:


jobs:
  
  build:
    
    runs-on: ubuntu-latest

    steps:
      
      - uses: central-organization/ci_repo/.github/actions/checkout_repo_with_submodules@actions-new
        with:
          repo: central-organization/master_repo
          token: ${{ secrets.SUPER_TOKEN }}
      - name: Show all
        run: git status